#!/bin/bash

#Automatically installs apt updates on your Ubuntu machine
#copyright fankijo

#set path variable
export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin

#If logged, theres the date
date

#update sourcelists
echo ""
echo "getting updates from sourcelists"
apt-get update

#install the updates
echo ""
echo "installing updates"
apt-get upgrade -y

#install dist upgrades
echo ""
echo "installing dist updates"
apt-get dist-upgrade -y

#delete packet cache
echo ""
echo "cleaning temp files"
apt-get clean -y

#uninstall no longer needed packages
echo ""
echo "uninstalling no longer needed pakages"
apt autoremove -y

#check if reboot is necessarry
#Remove the section below if you dont want this script to automatically reboot your machine
if [ -f "/var/run/reboot-required" ]
then
        echo ""
        echo "Reboot is required."
        echo "T minus 60 Sekunden"
        shutdown --reboot +1
else
        echo ""
        echo "No reboot required."
fi
